"""Updated the investment profile

Revision ID: 046f99dfc436
Revises: 68d577cf3e1c
Create Date: 2024-07-30 22:04:26.628615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046f99dfc436'
down_revision = '68d577cf3e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_investment_goal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_investment_goals', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('sustainable_investing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_existing_portfolio', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('open_to_higher_risk', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interested_in_growth_stocks', sa.Boolean(), nullable=True))
        batch_op.alter_column('education_level',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('investment_experience',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.alter_column('investment_experience',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('education_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('interested_in_growth_stocks')
        batch_op.drop_column('open_to_higher_risk')
        batch_op.drop_column('has_existing_portfolio')
        batch_op.drop_column('sustainable_investing')
        batch_op.drop_column('secondary_investment_goals')
        batch_op.drop_column('primary_investment_goal')

    # ### end Alembic commands ###
