"""Initial migration

Revision ID: 35a9fc6bebea
Revises: 
Create Date: 2024-07-27 15:45:31.577315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a9fc6bebea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_worth', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('investment_horizon', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('investment_experience', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('years_investing', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('risk_tolerance',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('risk_tolerance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('years_investing')
        batch_op.drop_column('investment_experience')
        batch_op.drop_column('investment_horizon')
        batch_op.drop_column('net_worth')

    # ### end Alembic commands ###
