"""empty message

Revision ID: 558696b2638b
Revises: 046f99dfc436
Create Date: 2024-07-30 23:23:36.621958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558696b2638b'
down_revision = '046f99dfc436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.drop_column('interested_in_growth_stocks')
        batch_op.drop_column('open_to_higher_risk')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investment_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_to_higher_risk', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('interested_in_growth_stocks', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
