"""describe your changes

Revision ID: 68d577cf3e1c
Revises: 31be055ede60
Create Date: 2024-07-30 15:21:42.793279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d577cf3e1c'
down_revision = '31be055ede60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_completed_survey', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_completed_survey')

    # ### end Alembic commands ###
