"""Update models

Revision ID: fffcbfa665f2
Revises: 35a9fc6bebea
Create Date: 2024-07-28 02:46:04.265313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffcbfa665f2'
down_revision = '35a9fc6bebea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_metadata',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('ceo', sa.String(length=100), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('debt', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('transaction_type', sa.String(length=4), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_ticker'), ['ticker'], unique=False)

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_stock_symbol')
        batch_op.create_index(batch_op.f('ix_stock_ticker'), ['ticker'], unique=False)
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_index(batch_op.f('ix_stock_ticker'))
        batch_op.create_index('ix_stock_symbol', ['symbol'], unique=False)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('current_price')
        batch_op.drop_column('company_name')
        batch_op.drop_column('ticker')

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_ticker'))

    op.drop_table('transaction')
    op.drop_table('stock_metadata')
    # ### end Alembic commands ###
